SIM_TIME = 60
GRID_SIZE = 50
MAX_PLANES = 8

PLANE_RADIUS = 2.2
COLLISION_RADIUS = PLANE_RADIUS * 2

# Possible future changes

RUNWAY_START = (GRID_SIZE // 2, GRID_SIZE - 1)
RUNWAY_END = (GRID_SIZE // 2, GRID_SIZE - 5)
SPAWN_FREQUENCUY = 1
